[config]
default_to_workspace = false



[tasks.setup]
description = "Prepare project for development"
dependencies = ["services:setup"]
command = "cargo"
args = ["build"]



[tasks."services:setup"]
description = "Pull Docker images for local services"
command = "docker"
args = ["compose", "-f", "compose.services.dev.yml", "pull"]

[tasks."services:up"]
description = "Start local services and wait until healthy"
command = "docker"
args = ["compose", "-f", "compose.services.dev.yml", "up"]

[tasks."services:down"]
description = "Stop local services"
command = "docker"
args = ["compose", "-f", "compose.services.dev.yml", "down"]



[tasks."dev:run"]
description = "Run server in development mode with hot reloading"
command = "cargo"
args = ["watch", "-x", "run"]



[tasks.fmt]
description = "Format the code"
dependencies = ["fmt:server", "fmt:lib"]

[tasks."fmt:server"]
description = "Format the server code"
command = "cargo"
args = ["fmt", "--all"]

[tasks."fmt:lib"]
description = "Format the lib code"
cwd = "lib"
command = "cargo"
args = ["fmt", "--all"]



[tasks.test]
description = "Run tests for server and lib"
dependencies = ["test:server", "test:lib"]

[tasks."test:server"]
description = "Run server tests"
command = "cargo"
args = ["test", "--all-targets"]

[tasks."test:lib"]
description = "Run lib tests"
cwd = "lib"
command = "cargo"
args = ["test", "--all-targets"]
